SELECT a.ITEM_ID, b.ITEM_NAME, b.RARITY
FROM ITEM_TREE a
JOIN ITEM_INFO b ON a.ITEM_ID = b.ITEM_ID
LEFT JOIN ITEM_TREE c ON c.PARENT_ITEM_ID = a.ITEM_ID
WHERE c.ITEM_ID IS NULL
ORDER BY a.ITEM_ID DESC
