SELECT a.APNT_NO, b.PT_NAME, a.PT_NO, a.MCDP_CD, c.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a JOIN PATIENT b ON a.PT_NO = b.PT_NO
JOIN DOCTOR c ON a.MDDR_ID = c.DR_ID
WHERE YEAR(a.APNT_YMD) = '2022' AND MONTH(a.APNT_YMD) = '4' AND DAY(a.APNT_YMD)='13'
AND a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD ASC;