SELECT a.ID, b.FISH_NAME, a.LENGTH
FROM FISH_INFO a
JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
WHERE a.LENGTH = (
    SELECT MAX(a2.LENGTH)
    FROM FISH_INFO a2
    WHERE a2.FISH_TYPE = a.FISH_TYPE)
ORDER BY a.ID ASC
