SELECT SUM(a.SCORE) AS SCORE, b.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
FROM HR_GRADE a JOIN HR_EMPLOYEES b
ON a.EMP_NO	= b.EMP_NO
WHERE a.YEAR = 2022
GROUP BY b.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
ORDER BY SCORE DESC
LIMIT 1;